const data = {
    products: [
      {
        _id: '1',
        name: 'Nike Wmns Air Max 90',
        category: 'Fashion',
        image: '/images/p1.jpg',
        price: 411, 
        countInStock:5,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Shower and body set',
        category: 'Spa',
        image: '/images/p2.jpg',
        price: 30,
        countInStock:10,
        brand: 'Lush Canada',
        rating: 4.0,
        numReviews: 10,
        description: 'Relaxation  product',
      },
      {
        _id: '3',
        name: 'Wireless In-Ear Headphones',
        category: 'Tech',
        image: '/images/p3.jpg',
        price: 220,
        countInStock:25,
        brand: 'JBl',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality sound product',
      },
      {
        _id: '4',
        name: 'Water Bottles 1L',
        category: 'Basics',
        image: '/images/p4.jpg',
        price: 78,
        countInStock:15,
        brand: 'UZSPACE',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Photo Frame Acrylic Music',
        category: 'Home Decor',
        image: '/images/p5.jpg',
        price: 65,
        countInStock:0,
        brand: 'Decorator',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Christmas Hoodie',
        category: 'Fashion',
        image: '/images/p6.jpg',
        price: 40,
        countInStock:35,
        brand: 'Amazon Basics',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;